### ISSUE TITLE
[ Desktop - Current Resolution ] Sizes does not match

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#11]
The sizes of the icon does not match in desktop
![from-trello](https://user-images.githubusercontent.com/37136794/37812621-dc829c64-2e9b-11e8-8359-4d8d3c9e94c8.png)
![from-production](https://user-images.githubusercontent.com/37136794/37812622-dcb04ca4-2e9b-11e8-8506-deed53571894.png)

**Comment by kevinpayas** [comment]
adjust sizes
