### ISSUE TITLE
[ Desktop - Current Resolution ] Margin not enough

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#13]
Margin from the page does not match in the psd file

![from-page](https://user-images.githubusercontent.com/37136794/37812828-0260b79e-2e9d-11e8-8741-82d963778577.png)
![from-trello](https://user-images.githubusercontent.com/37136794/37812829-028a4ea6-2e9d-11e8-8245-e040985f6ec6.png)

**Comment by kevinpayas** [comment]
adjusted margin
