### ISSUE TITLE
[ Desktop - 1920x1080 ] Needs a padding on the sides

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#14]
![from-page](https://user-images.githubusercontent.com/37136794/37813036-5512c198-2e9e-11e8-8f73-aa9fa7394fa8.png)
![from-trello](https://user-images.githubusercontent.com/37136794/37813037-553ad020-2e9e-11e8-8e41-7b753c38c068.png)

**Comment by kevinpayas** [comment]
padding on the sides fixed
