### ISSUE TITLE
[Desktop - 1920x1080] Hero container height

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#15]
Hero container height is smaller than in template. Tested on 1920x1080.

Merged:
![contacthero](https://user-images.githubusercontent.com/37566652/37813937-c299dd34-2e24-11e8-8859-5199574b1a30.PNG)

Template:
![contactherotemplate](https://user-images.githubusercontent.com/37566652/37814091-5fc032fc-2e25-11e8-9e34-3ba8c7fbb7e2.PNG)

Output:
![contactherooutput](https://user-images.githubusercontent.com/37566652/37814111-78de869e-2e25-11e8-8d96-daa193eddedf.PNG)

**Comment by kevinpayas** [comment]
Hero container height adjusted
