### ISSUE TITLE
[Desktop - 1920x1080] Support section columns structure

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#16]
Left column and right column doesn't match in the template. Tested on 1920x1080.

Merged:
![contactsupportsection](https://user-images.githubusercontent.com/37566652/37814378-ed125210-2e26-11e8-9438-da87f75a60f0.PNG)

Template:
![contactsupportsectiontemplate](https://user-images.githubusercontent.com/37566652/37814452-50d31424-2e27-11e8-85e5-c20343b4782c.PNG)

Output:
![contactsupportsectionoutput](https://user-images.githubusercontent.com/37566652/37814434-2d03df2e-2e27-11e8-8c09-dd9cf5f10dfe.PNG)

**Comment by kevinpayas** [comment]
upport section columns structure fixed
