### ISSUE TITLE
[Desktop - 1920x1080] Contact form size

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#17]
Contact form size is bigger than in template.

Merged:
![contactform](https://user-images.githubusercontent.com/37566652/37814661-58f6f6c4-2e28-11e8-9280-e00a04a98b9a.PNG)

Template:
![contactformtemplate](https://user-images.githubusercontent.com/37566652/37814727-adc26d46-2e28-11e8-95ca-7c672bb818c7.PNG)

Output:
![contactformoutput](https://user-images.githubusercontent.com/37566652/37814703-9051bc30-2e28-11e8-9059-be652160ea46.PNG)

**Comment by kevinpayas** [comment]
contact form size fixed
