### ISSUE TITLE
[Footer] Overall font-size/font-style

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#2]
Overall font-size and font-style is a little bit off. Tested on 1920x1508.

Merged:
![footerfonts](https://user-images.githubusercontent.com/37566652/37760500-d60db472-2df1-11e8-94d2-8a94aeb82ff7.PNG)

Template:
![footerfontsoutput](https://user-images.githubusercontent.com/37566652/37760714-6f45e376-2df2-11e8-9378-6626f8426d14.PNG)

Output:
![footerfontstemplate](https://user-images.githubusercontent.com/37566652/37760604-1c06529a-2df2-11e8-8d2a-4749c13edf39.PNG)

**Comment by jlimpahan** [comment]
Font-style and font-sizes appears to be similar to the template.
