### ISSUE TITLE
[Mobile - 320x1080] Hero container height

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#20]
Hero container is larger than in template. Tested on 320x1080.

Merged:
![contactmobilehero](https://user-images.githubusercontent.com/37566652/37816370-0a8b48e8-2e30-11e8-82e9-ab8ad081a8a0.PNG)

Template:
![contactmobileherotemplate](https://user-images.githubusercontent.com/37566652/37816409-2dad35a2-2e30-11e8-8bcb-8483477c6c82.PNG)

Output:
![contactmobileherooutput](https://user-images.githubusercontent.com/37566652/37816439-4fce50da-2e30-11e8-9c4a-047ea6d7df73.PNG)

**Comment by kevinpayas** [comment]
Hero container height fixed
