### ISSUE TITLE
[Mobile - 320x1080] Support text section left margin

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#21]
Excess left margin.

Merged:
![contactmobilesupport](https://user-images.githubusercontent.com/37566652/37816878-e7ee815e-2e31-11e8-8141-12d1c0b93b49.PNG)

Output:
![contactmobilesupportoutput](https://user-images.githubusercontent.com/37566652/37817036-8258577e-2e32-11e8-84cf-1189f0af3a68.PNG)

Template:
![contactmobilesupporttemplate](https://user-images.githubusercontent.com/37566652/37817004-617094f4-2e32-11e8-8ed6-0a1a0b976a1d.PNG)

**Comment by kevinpayas** [comment]
left margin fixed
