### ISSUE TITLE
[Web] Contact Us - Not Properly Align

### ISSUE THREAD

**Issue by miksilva11** [gabrieljayhuerte/ibinex-i#23]
- Not Properly Align

![error](https://user-images.githubusercontent.com/37648510/37820285-3e29f6aa-2ed4-11e8-97fc-0a3a6a89e5ba.png)

Expected Output:
![contact us alignment](https://user-images.githubusercontent.com/37648510/37820183-fd5eadd2-2ed3-11e8-9b82-8c9dda45fbaf.png)

**Comment by kevinpayas** [comment]
Text properly aligned..
