### ISSUE TITLE
[Footer] Container height

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#3]
Footer container height (padding? margin?) way off. Tested on 1920x1508.

Merged:
![footerheight](https://user-images.githubusercontent.com/37566652/37761642-330d9b80-2df5-11e8-89e7-86fa3fd7078d.PNG)

Template:
![footerheighttemplate](https://user-images.githubusercontent.com/37566652/37761998-2cbfb50a-2df6-11e8-88b8-bc49361b23e0.PNG)

Output:
![footerheightoutput](https://user-images.githubusercontent.com/37566652/37761948-037c7a3e-2df6-11e8-8eff-821f642ce74e.PNG)

**Comment by jlimpahan** [comment]
Fixed padding bottom set to 1.5rem <3
