### ISSUE TITLE
[Footer] Newsletter signup form size

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#4]
Footer newsletter signup size (length and width) is smaller than in template. Tested in 1920x1508.

Merged:
![footernewsletter](https://user-images.githubusercontent.com/37566652/37762712-18507300-2df8-11e8-9244-be2c4a141cb3.PNG)

Template:
![footernewslettertemplate](https://user-images.githubusercontent.com/37566652/37762777-3de4bd56-2df8-11e8-8902-cca4ee651700.PNG)

Output:
![footernewsletteroutput](https://user-images.githubusercontent.com/37566652/37762829-5f9b1c38-2df8-11e8-95d5-d3d236724dbe.PNG)

**Comment by jlimpahan** [comment]
Set the height of the input text to 53px and set the height of the button to 54px so that it looks like it overlapped the input textbox.
