### ISSUE TITLE
[Mobile - 320x1080] Contact form size

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#40]
Contact form size is bigger than in template.

Merged:
![contactmobileform](https://user-images.githubusercontent.com/37566652/37823023-74b39012-2e45-11e8-8428-fd53226f3680.PNG)

Template:
![contactmobileformtemplate](https://user-images.githubusercontent.com/37566652/37822972-52da5b1a-2e45-11e8-9d9f-6d8e4cc39546.PNG)

Output:
![contactmobileformoutput](https://user-images.githubusercontent.com/37566652/37823069-9a27ca7a-2e45-11e8-9aeb-6a4c1063c401.PNG)

**Comment by kevinpayas** [comment]
Form fixed
