### ISSUE TITLE
[Footer] Main content width

### ISSUE THREAD

**Issue by jctiru-ibinex** [gabrieljayhuerte/ibinex-i#5]
Footer main content width on the template is wider. Tested on 1920x1508.

Merged:
![footermaincontentwidth](https://user-images.githubusercontent.com/37566652/37764685-4753b4e6-2dfd-11e8-9d83-64161308a260.PNG)

Template:
![footermaincontentwidthtemplate](https://user-images.githubusercontent.com/37566652/37764913-df9e8190-2dfd-11e8-950f-26c39a4ba534.PNG)

Output:
![footermaincontentwidthoutput](https://user-images.githubusercontent.com/37566652/37764972-fbe1e842-2dfd-11e8-98b5-cd600c2d7aee.PNG)

**Comment by jlimpahan** [comment]
Fixed.
