### ISSUE TITLE
[ Desktop 1920x1080 ] Color 

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#52]
The color must be grey
![color-grey](https://user-images.githubusercontent.com/37136794/37955855-4965289a-31dc-11e8-8bc1-11c07adcc3a3.png)

**Comment by ricky-cabugawan** [comment]
fixed color issue in desktop

commit:
https://github.com/gabrieljayhuerte/ibinex-i/commit/e733f5b3c698c9958ecec94eefdad480f65b2a2f
