### ISSUE TITLE
[ Desktop - 8K ] Responsiveness of Header

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#54]
![too-small-8k](https://user-images.githubusercontent.com/37136794/38020099-f54e1bba-32ab-11e8-845d-afb282da7e07.png)

**Comment by jjrsabanal** [comment]
The issue here is with bootstrap 4. It can not expand anymore because bootstrap 4 maximum width is up to 1200 only
