### ISSUE TITLE
[ Desktop 1280x800 ] Padding, Margins, and Size

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#61]
- The image and the header has less space on the psd ( yellow ) 
- The text should only cover the square area ( yellow )
- The button must be higher than the bottom of the image ( red )
- The font weight of button is lighter on the psd ( green)

![screenshot 2](https://user-images.githubusercontent.com/37136794/38286605-d1b011de-37f8-11e8-9a50-86a93f6b88e0.png)

**Comment by rlbayeta** [comment]
Done - Tested in responsiveness from large screen to medium screen.
