### ISSUE TITLE
[ Desktop 1280x800 ] font-weight

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#62]
The font-weight on the psd is much lighter compared to actual

![screenshot 3](https://user-images.githubusercontent.com/37136794/38286701-441b4c52-37f9-11e8-8026-cc550a262629.png)

**Comment by rlbayeta** [comment]
No. Can't do.

The next lighter font-weight is this.
![image](https://user-images.githubusercontent.com/37136843/38292077-f8268886-3814-11e8-8948-87bf7d169fa1.png)
There are no in-betweens.
