### ISSUE TITLE
 [ Desktop 1280x900 ] Font-Size

### ISSUE THREAD

**Issue by gabrieljayhuerte** [gabrieljayhuerte/ibinex-i#63]
This part sure covers a huge space compared to the psd. Please review if we can lessen the space. This doesn't look good 
![screenshot 4](https://user-images.githubusercontent.com/37136794/38286772-a72b6d90-37f9-11e8-98a8-73a7ad286e18.png)

**Comment by rlbayeta** [comment]
Done - Tested the responsiveness from BIIIG Screen to Medium Screen - 

Please check if there are still issues
