### ISSUE TITLE
[web] Navigation Bar - Navigation links too close from nav-brand

### ISSUE THREAD

**Issue by miksilva11** [gabrieljayhuerte/ibinex-i#8]
template:
![1](https://user-images.githubusercontent.com/37648510/37767221-7828ffa2-2e1d-11e8-898c-a8ff2c2f4489.PNG)

![2](https://user-images.githubusercontent.com/37648510/37767238-827000a0-2e1d-11e8-83f9-64ca6b861a5c.PNG)

**Comment by kevinpayas** [comment]
nav bar links add padding
